services:
  api:
    container_name: flashslidesai_api
    build:
      context: .
      dockerfile: ./src/api/environment/Dockerfile.local
    ports:
      - "3001:3001"
    volumes:
      - ./src/api:/api
      - ./src/common:/common
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - localstack

  app:
    container_name: flashslidesai_app
    build:
      context: .
      dockerfile: ./src/app/environment/Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - ./src/app:/app
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - api
      - localstack

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    env_file:
      - .env
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts:/etc/localstack/init/ready.d"
    networks:
      - app_network


volumes:
  shared_storage:
    driver: local
  cache:
    driver: local

networks:
  app_network:
    driver: bridge